default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: gocardless
  password:

development:
  <<: *default
  database: prayers_development

test:
  <<: *default
  database: prayers_test
